<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class sigmel_informacion_libro2_libro3_eventos extends Model
{
    //use HasFactory;

    public $timestamps =false;

    protected $primaryKey= 'Id_Libros';

    protected $fillable = [
        'ID_evento',
        'Id_Asignacion',
        'Id_proceso',
        'Conducta10',
        'Conducta11',
        'Conducta12',
        'Conducta13',
        'Conducta14',
        'Conducta15',
        'Conducta16',
        'Conducta17',
        'Conducta18',
        'Conducta19',
        'Total_conducta',
        'Comunicacion20',
        'Comunicacion21',
        'Comunicacion22',
        'Comunicacion23',
        'Comunicacion24',
        'Comunicacion25',
        'Comunicacion26',
        'Comunicacion27',
        'Comunicacion28',
        'Comunicacion29',
        'Total_comunicacion',
        'Personal30',
        'Personal31',
        'Personal32',
        'Personal33',
        'Personal34',
        'Personal35',
        'Personal36',
        'Personal37',
        'Personal38',
        'Personal39',
        'Total_personal',
        'Locomocion40',
        'Locomocion41',
        'Locomocion42',
        'Locomocion43',
        'Locomocion44',
        'Locomocion45',
        'Locomocion46',
        'Locomocion47',
        'Locomocion48',
        'Locomocion49',
        'Total_locomocion',
        'Disposicion50',
        'Disposicion51',
        'Disposicion52',
        'Disposicion53',
        'Disposicion54',
        'Disposicion55',
        'Disposicion56',
        'Disposicion57',
        'Disposicion58',
        'Disposicion59',
        'Total_disposicion',
        'Destreza60',
        'Destreza61',
        'Destreza62',
        'Destreza63',
        'Destreza64',
        'Destreza65',
        'Destreza66',
        'Destreza67',
        'Destreza68',
        'Destreza69',
        'Total_destreza',
        'Situacion70',
        'Situacion71',
        'Situacion72',
        'Situacion73',
        'Situacion74',
        'Situacion75',
        'Situacion76',
        'Situacion77',
        'Situacion78',
        'Total_situacion',
        'Total_discapacidad',
        'Orientacion',
        'Idenpendencia_fisica',
        'Desplazamiento',
        'Ocupacional',
        'Integracion',
        'Autosuficiencia',
        'Edad_cronologica',
        'Total_minusvalia',
        'Nombre_usuario',
        'F_registro',
    ];
}
